#!/bin/sh
#MIRT+LASSO.sh
#Slurm script to run R program that generates graph of discrete Delta-hedging call

#Slurm directives
#
#SBATCH --account=stats      # The account name for the job.
#SBATCH --job-name=hedge    # The job name.
#SBATCH -c 1                     # The number of cpu cores to use.
#SBATCH --time=48:00:00              # The time the job will take to run.
#SBATCH --mem-per-cpu=16gb        # The memory the job will use per cpu core.
#SBATCH --array=1-961
module load R

#Command to execute R code
R CMD BATCH --no-save --vanilla MIRT+LASSO.R MIRT+LASSOout
# End of script
